apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
spec:
  selector:
    matchlabels:
      app: "2048"
  replicas: 2
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: ntsehebert/2048-game
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 8080
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata: 
  name: service-2048
  labels:
    app: servicelabel
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 8080
  selector:
    app: "2048"

